# Maintainer: fffzlfk <fffzlfk@qq.com>
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=hex-rs-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="A simple command line hex viewer written in Rust."
url="https://github.com/fffzlfk/hex-rs"
license=("MIT")
arch=("x86_64")
provides=("hex-rs")
conflicts=("hex-rs")
source=("https://github.com/fffzlfk/hex-rs/releases/download/v$pkgver/hex-rs-$pkgver-x86_64.tar.gz")
sha256sums=("4ede15382bb99d18d7d6840eefa86a922da9cc58e647642cd29e9b825e379b32")

package() {
    install -Dm755 hex-rs -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
