# Maintainer: fffzlfk <fffzlfk@qq.com>
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=hex-rs-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="A simple command line hex viewer written in Rust."
url="https://github.com/fffzlfk/hex-rs"
license=("MIT")
arch=("x86_64")
provides=("hex-rs")
conflicts=("hex-rs")
source=("https://github.com/fffzlfk/hex-rs/releases/download/v$pkgver/hex-rs-$pkgver-x86_64.tar.gz")
sha256sums=("33bb0cc77e4be7da90c585027c5c942993bb8c6ce43321f0432886e1999e621a")

package() {
    install -Dm755 hex-rs -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}